# Document:
# http://simiki.org/docs/configuration.html

url: wiki.man1ac.me
title: Ender | Wiki
keywords: wiki, Linux
description: 
author: Ender
root: /mywiki
theme: yasimple

deploy: 
    - type: git
      remote: origin
      branch: gh-pages
          
